<!DOCTYPE html>
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="stylesheet.css" />
        <title>Clear</title>
    </head>
    <body>
        <header>
            <span class="corner1">header;</span><span class="corner2">/header;</span>
        </header>
        <nav><span class="corner1">nav;</span><span class="corner2">/nav;</span></nav><!--
        --><section>
            <span class="corner1">section;</span><span class="corner2">/section;</span>
            <article>
                <span class="corner1">article;</span><span class="corner2">/article;</span>
            </article>
            <aside>
                <span class="corner1">aside;</span><span class="corner2">/aside;</span>
            </aside>
            <footer>
                <span class="corner1">footer;</span><span class="corner2">/footer;</span>
            </footer>
        </section>
        <footer>
            <span class="corner1">footer;</span><span class="corner2">/footer;</span>
        </footer>
    </body>
</html>
