<form class="plat" action="" method="POST">
	<label for="Plats">Ingrédients pour chaque plat</label>
	<label>Nom du plat</label>
	<input type="text" name="nom" value="nom">
	<label>Prix</label>
	<input type="text" name="prix" value="prix">
	<label>Catégorie</label>
	<select name="categorie">
		<?php 
			foreach ($listeCategorie as $categorie) {

			echo '<option value="' . $categorie["id_categorie"] . ' ">' . $categorie["nom"] . '</option>';
			}
		?>

	</select>


	<fieldset id="ingredients-form">

	<select id="ingredients-list">
		<?php
			foreach ($listeIngredients as $ingredient) {

			echo '<option value="' . $ingredient["id_ingredient"] .'">' . $ingredient['designation'] . '</option>';
			}
		?>
	</select>
	<label>Quantite</label>
	<input type="text" name="quantite" value="quantite">


	<button id="add-ingredient">Ajouter un ingrédient et une quantité</button>
	<div id="hidden-fields">

	</div>

	<ul id="selected-ingredients">
	
	</ul>
	</fieldset>
  	<input type="submit" name="Ajouter">
</form>