<form class="plat" action="" method="POST">
	<label for="Plats">Ingrédients pour chaque plat</label>
	<label>Nom du plat</label>
	  <input type="text" name="nom" value="nom">
	  <label>Prix</label>
	  <input type="text" name="prix" value="prix">
	  <label>Catégorie</label>
	  <select>
	  	<?php 
		foreach ($listeCategorie as $categorie) {

			echo '<option>' . $categorie["nom"] . '</option>';
		}
		?>

	  </select>
  	<input type="submit" name="Ajouter">
</form>