<form class="menu" action="" method="POST">

	<input type="text" name="nom_menu" value="menu medium">
	<label>Entrées : </label>
	<select name="entree">
		<?php 
			foreach ($listeEntrees as $entree) {

			echo '<option value="' . $entree['id_plat'] . ' ">' . $entree["nom"] . '</option>';
			}
		?>

	</select>

	<select name="plat">
		<?php 
			foreach ($listePlats as $plat) {

			echo '<option value="' . $plat['id_plat'] . ' ">' . $plat["nom"] . '</option>';
			}
		?>

	</select>

	<select name="dessert">
		<?php 
			foreach ($listeDesserts as $dessert) {

			echo '<option value="' . $dessert['id_plat'] . ' ">' . $dessert["nom"] . '</option>';
			}
		?>

	</select>


	<input type="text" name="prix_menu" value="15">

	<input type="submit" name="Valider" value="Valider mon menu">

</form>