<form class="plat" action="ingredient/new" method="POST">
	<label for="Quel ingrédient souhaitez-vous ?">Quel ingrédient souhaitez-vous ?</label>
	<label>Désignation</label>
	  <input type="text" name="designation" value="Désignation">
	  <label>Type</label>
	  <input type="text" name="type" value="Type">
	  <label>Stock</label>
	  <input type="text" name="stock" value="Stock">
	  <label>Prix</label>
	  <input type="text" name="prix" value="Prix">
	  <label>Date péremption</label>
	  <input type="text" name="date_peremption" value="Date de péremption">
  <button>Ajouter</button>
</form>
