<h1>Création d'un compte utilisateur</h1>

<form>
	<label>Entrez votre pseudo</label>
	<input type="text" name="pseudo" value="pseudo">
	</br>

	<label>Entrez votre mot de passe</label>
	<input type="password" name="password" value="password">

	<label>Entrez votre nom</label>
	<input type="text" name="nom" value="nom">

	<label>Entrez votre prénom</label>
	<input type="text" name="prenom" value="prenom">
	
	<input type="submit" name="Envoyer">

	</form>
</form>