<h2>Détails du plat</h2>

	<ul>
	<?php 
			echo '<li>Nom du plat : ' . $plat["nom_plat"] . '</li><li>Prix du plat : ' . $plat["prix"] . '</li><li>Catégorie du plat : ' . $plat["nom_categorie"] . '</li><p>Ingrédients : </p>'; 
		
			echo '<ul>';
			foreach ($ingredients as $ingredient) {
				echo '<li>' . $ingredient['designation'] . '</li>' . '<li>Quantité : ' . $ingredient['quantite'] . '</li></br>';
			}
			echo '</ul>';
	?>

	</ul>
